# Generated by Django 4.0.3 on 2022-04-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(default=models.CharField(db_index=True, max_length=255, unique=True), unique=True, verbose_name='URL-Адрес'),
        ),
    ]
