# Generated by Django 4.0.3 on 2022-04-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL-Адрес'),
        ),
    ]
