# Generated by Django 4.0.3 on 2022-03-10 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-Адрес')),
            ],
            options={
                'verbose_name': 'Категория',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorComment', models.CharField(max_length=255, verbose_name='Автор комментария')),
                ('body', models.TextField(blank=True, verbose_name='Тело комментария')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания комментария')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок тэга')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-Адрес')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=150, verbose_name='Имя пользователя')),
                ('isAdmin', models.BooleanField(default=False, verbose_name='Является ли админом пользователь?')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-Адрес')),
            ],
            options={
                'ordering': ['author'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок поста')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-Адрес')),
                ('сontent', models.TextField(blank=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания публикации')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('isPublished', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('views', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('likes', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.category')),
                ('tags', models.ManyToManyField(blank='true', related_name='posts', to='blog.tags')),
            ],
            options={
                'ordering': ['createdAt'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок блога')),
                ('desc', models.TextField(blank=True, verbose_name='Описание блога')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания блога')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Дата последней публикации')),
                ('owner', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True, verbose_name='URL-Адрес')),
                ('author', models.ManyToManyField(to='blog.user')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
