# Generated by Django 4.0.3 on 2022-03-22 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeArticle',
        ),
        migrations.DeleteModel(
            name='LikeComment',
        ),
    ]
